def benchmark_primitives(iterations, /): ...
def error_union_int(value, should_error, /): ...
def mixed_types(int_val, float_val, bool_val, str_val, /): ...
def optional_int(value, /): ...
def return_bool(value, /): ...
def return_f64(value, /): ...
def return_i64(value, /): ...
def return_string(value, /): ...
