import numpy as np
from numpy.typing import NDArray

def create_zeros(size: int) -> NDArray[np.float64]: ...
def create_ones(rows: int, cols: int) -> NDArray[np.float64]: ...
def from_slice(values: list[float]) -> NDArray[np.float64]: ...
def double_array(arr: NDArray[np.float64]) -> NDArray[np.float64]: ...
def sum_array(arr: NDArray[np.float64]) -> float: ...
def calculate_mean(arr: NDArray[np.float64]) -> float: ...
def array_stats(arr: NDArray[np.float64]) -> dict[str, float]: ...
def reshape_array(arr: NDArray[np.float64], rows: int, cols: int) -> NDArray[np.float64]: ...
def flatten_array(arr: NDArray[np.float64]) -> NDArray[np.float64]: ...
def transpose_array(arr: NDArray[np.float64]) -> NDArray[np.float64]: ...
def array_info(arr: NDArray[np.float64]) -> dict[str, int | str]: ...
def add_arrays(a: NDArray[np.float64], b: NDArray[np.float64]) -> NDArray[np.float64]: ...

class ArrayProcessor:
    """A class for processing NumPy arrays"""
    def __init__(self, arr: NDArray[np.float64]) -> None: ...
    def get_array(self) -> NDArray[np.float64]: ...
    def double(self) -> NDArray[np.float64]: ...
    def sum(self) -> float: ...
    def mean(self) -> float: ...
