def array_info(arr, /): ...
def array_stats(arr, /): ...
def create_array(): ...
def create_ones(rows, cols, /): ...
def create_zeros(rows, cols, /): ...
def double_array(arr, /): ...
def elementwise_multiply(a, b, /): ...
def fast_sum(arr, /): ...
def get_shape(arr, /): ...
def get_strides(arr, /): ...
def numpy_available(): ...
