def batch_add(a, b, /): ...
def vec4_add(a, b, /): ...
def vec4_distance(a, b, /): ...
def vec4_dot(a, b, /): ...
def vec4_max(vec, /): ...
def vec4_min(vec, /): ...
def vec4_scale(vec, scalar, /): ...
def vec4_sum(vec, /): ...
