"""
Simple project initialization for pyz3.

Creates a minimal project structure without external dependencies.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""

import os
import subprocess
import sys
from pathlib import Path
from typing import Optional

from pyz3.logging_config import get_logger
from pyz3.security import SecurityValidator

logger = get_logger(__name__)


def init_project(
    path: Path,
    package_name: Optional[str] = None,
    author_name: Optional[str] = None,
    author_email: Optional[str] = None,
    description: Optional[str] = None,
    **kwargs
) -> None:
    """
    Initialize a new pyz3 project with minimal structure.

    Args:
        path: Directory to initialize the project in
        package_name: Name of the package (defaults to directory name)
        author_name: Author name (defaults to git config)
        author_email: Author email (defaults to git config)
        description: Project description
    """
    logger.info(f"Initializing pyz3 project in {path}")

    # Determine project name
    if package_name is None:
        package_name = path.name.replace("-", "_").lower()

    # Validate package name
    is_valid, error, sanitized_name = SecurityValidator.sanitize_package_name(package_name)
    if not is_valid:
        logger.error(f"Invalid package name: {error}")
        print(f"❌ Error: {error}")
        sys.exit(1)

    package_name = sanitized_name

    # Create project directory if it doesn't exist
    path.mkdir(parents=True, exist_ok=True)

    # Get git user info
    git_name, git_email_full = get_git_user_info()
    if author_name is None:
        author_name = git_name.split("<")[0].strip() if "<" in git_name else git_name
    if author_email is None and "<" in git_email_full:
        author_email = git_email_full.split("<")[1].rstrip(">").strip()
    elif author_email is None:
        author_email = "your.email@example.com"

    if description is None:
        description = f"A pyz3 extension module"

    # Create project structure
    create_project_structure(
        path,
        package_name=package_name,
        author_name=author_name,
        author_email=author_email,
        description=description,
    )

    print(f"\n✅ Project '{package_name}' initialized successfully at {path}")
    print(f"\nNext steps:")
    print(f"  cd {path}")
    print(f"  # Edit {package_name}.zig")
    print(f"  zig build")
    print(f"  pytest")

    logger.info("Project initialized successfully")


def create_project_structure(
    path: Path,
    package_name: str,
    author_name: str,
    author_email: str,
    description: str,
):
    """Create minimal project structure."""

    # Create directories
    (path / "test").mkdir(exist_ok=True)

    # Create main Zig file
    zig_content = f'''const py = @import("pyz3");

pub fn hello(args: struct {{ name: []const u8 }}) ![]const u8 {{
    return "Hello, " ++ args.name ++ "!";
}}

pub fn add(args: struct {{ a: i64, b: i64 }}) i64 {{
    return args.a + args.b;
}}

comptime {{
    py.rootmodule(@This());
}}
'''
    (path / f"{package_name}.zig").write_text(zig_content)

    # Create pyproject.toml
    pyproject_content = f'''[build-system]
requires = ["pyz3"]
build-backend = "pyz3.build"

[project]
name = "{package_name}"
version = "0.1.0"
description = "{description}"
authors = [
    {{name = "{author_name}", email = "{author_email}"}}
]
requires-python = ">=3.11"
dependencies = [
    "pyz3",
]

[tool.pyz3]
root = "."
build_zig = "build.zig"

[[tool.pyz3.ext_module]]
name = "{package_name}"
root = "{package_name}.zig"

[tool.pytest.ini_options]
testpaths = ["test"]
'''
    (path / "pyproject.toml").write_text(pyproject_content)

    # Create build.zig (will be auto-generated by pyz3)
    # We don't create it here as pyz3 will generate it

    # Create test file
    test_content = f'''import pytest
import {package_name}


def test_hello():
    """Test hello function."""
    result = {package_name}.hello("World")
    assert result == "Hello, World!"


def test_add():
    """Test add function."""
    result = {package_name}.add(5, 3)
    assert result == 8
'''
    (path / "test" / f"test_{package_name}.py").write_text(test_content)

    # Create README.md
    readme_content = f'''# {package_name}

{description}

## Installation

```bash
pip install -e .
```

## Development

```bash
# Build the extension
zig build

# Run tests
pytest

# Or use zigimport for automatic compilation
python -c "import pyz3.zigimport; import {package_name}; print({package_name}.hello('World'))"
```

## Usage

```python
import {package_name}

print({package_name}.hello("World"))
print({package_name}.add(5, 3))
```
'''
    (path / "README.md").write_text(readme_content)

    # Create .gitignore
    gitignore_content = '''# Python
__pycache__/
*.py[cod]
*.so
*.egg-info/
dist/
build/
.pytest_cache/

# Zig
zig-cache/
zig-out/
build.zig
pyz3.build.zig

# IDE
.idea/
.vscode/
*.swp
'''
    (path / ".gitignore").write_text(gitignore_content)


def get_git_user_info() -> tuple[str, str]:
    """Get git user name and email if available."""
    name = "Your Name"
    email_full = "Your Name <your.email@example.com>"

    try:
        git_name = subprocess.check_output(
            ["git", "config", "user.name"],
            stderr=subprocess.DEVNULL,
            text=True,
            timeout=5,
        ).strip()
        git_email = subprocess.check_output(
            ["git", "config", "user.email"],
            stderr=subprocess.DEVNULL,
            text=True,
            timeout=5,
        ).strip()
        if git_name and git_email:
            name = git_name
            email_full = f"{git_name} <{git_email}>"
            logger.debug(f"Detected git user: {email_full}")
    except (subprocess.TimeoutExpired, subprocess.CalledProcessError, FileNotFoundError):
        logger.debug("Git config not available, using defaults")
    except Exception as e:
        logger.warning(f"Unexpected error getting git info: {e}")

    return name, email_full


def new_project(name: str, path: Optional[Path] = None) -> None:
    """
    Create a new pyz3 project in a new directory.

    Args:
        name: Name of the project
        path: Parent directory (defaults to current directory)
    """
    logger.info(f"Creating new project: {name}")

    if path is None:
        path = Path.cwd()

    is_valid, error, sanitized_name = SecurityValidator.sanitize_package_name(name)
    if not is_valid:
        logger.error(f"Invalid project name: {error}")
        print(f"❌ Error: {error}")
        sys.exit(1)

    project_path = path / sanitized_name

    if project_path.exists():
        logger.error(f"Directory already exists: {sanitized_name}")
        print(f"❌ Error: Directory '{sanitized_name}' already exists!")
        sys.exit(1)

    logger.debug(f"Creating project at {project_path}")
    init_project(project_path, package_name=sanitized_name)


# Backward compatibility
init_project_cookiecutter = init_project
